export enum EEmailErrMessage {
  INVALID = "INVALID_EMAIL",
  EMPTY = "EMPTY_EMAIL",
  MIN_LENGTH = "MIN_LENGTH_EMAIL",
  MAX_LENGTH = "MAX_LENGTH_EMAIL",
}

export enum EUserNameErrMessage {
  INVALID = "INVALID_USERNAME",
  EMPTY = "EMPTY_USERNAME",
  MIN_LENGTH = "MIN_LENGTH_USERNAME",
  MAX_LENGTH = "MAX_LENGTH_USERNAME",
}

export enum EPasswordErrMessage {
  INVALID = "INVALID_PASSWORD",
  EMPTY = "EMPTY_PASSWORD",
  MIN_LENGTH = "MIN_LENGTH_PASSWORD",
  MAX_LENGTH = "MAX_LENGTH_PASSWORD",
}

export enum EFullNameErrMessage {
  INVALID = "INVALID_FULLNAME",
  EMPTY = "EMPTY_FULLNAME",
  MIN_LENGTH = "MIN_LENGTH_FULLNAME",
  MAX_LENGTH = "MAX_LENGTH_FULLNAME",
}

export enum EDisplayNameErrMessage {
  INVALID = "INVALID_DISPLAYNAME",
  EMPTY = "EMPTY_DISPLAYNAME",
  MIN_LENGTH = "MIN_LENGTH_DISPLAYNAME",
  MAX_LENGTH = "MAX_LENGTH_DISPLAYNAME",
}

export enum EPhotoErrMessage {
  INVALID = "INVALID_PHOTO",
  EMPTY = "EMPTY_PHOTO",
  MIN_LENGTH = "MIN_LENGTH_PHOTO",
  MAX_LENGTH = "MAX_LENGTH_PHOTO",
}

export enum EUserIdErrMessage {
  INVALID = "INVALID_USERID",
  EMPTY = "EMPTY_USERID",
  MIN_LENGTH = "MIN_LENGTH_USERID",
  MAX_LENGTH = "MAX_LENGTH_USERID",
}

export enum ERefreshTokenErrMessage {
  INVALID = "INVALID_REFRESH_TOKEN",
  EMPTY = "EMPTY_REFRESH_TOKEN",
  MIN_LENGTH = "MIN_LENGTH_REFRESH_TOKEN",
  MAX_LENGTH = "MAX_LENGTH_REFRESH_TOKEN",
}

export enum EIdErrMessage {
  INVALID = "INVALID_ID",
  EMPTY = "EMPTY_ID",
  MIN_LENGTH = "MIN_LENGTH_ID",
  MAX_LENGTH = "MAX_LENGTH_ID",
}
